### ISSUE TITLE
changes  not saved in Redmine 4.0.4

### ISSUE THREAD

**Issue by koren85** [nanego/redmine_customize_core_fields#10]
With any settings, the save button does not save the selected settings. There are no errors in the logs. Redmine 4.0.4

**Comment by ejolivet** [comment]
I have the same issue on Redmine 4.0.3
When i look in the database,  i don't see the core_fields table. I'll try to figure out what's wrong with migration during plugin installation

**Comment by Daradaal** [comment]
I have the same issue on redmine 4.0.5 ? do you have a solution

**Comment by nanego** [comment]
Hello
I currently use this plugin in production with Redmine 4. We did not encountered this problem.
Can you please be more specific and describe how to reproduce your issue?

**Comment by axl89** [comment]
I'm also experiencing this issue in 4.0.7. With redmine in debug mode, I get the following when pressing the "Save" button in the administration link, when attempting to modify the "Private" field (http://localhost:8080/core_fields/5/edit) :


```
redmine_1  | 172.27.0.1 - - [21/Apr/2020:19:04:05 UTC] "POST /core_fields/is_private HTTP/1.1" 302 106
redmine_1  | http://localhost:8080/core_fields/5/edit -> /core_fields/is_private
redmine_1  | I, [2020-04-21T19:03:55.724336 #1]  INFO -- :   Rendered admin/_menu.html.erb (2.8ms)
redmine_1  | I, [2020-04-21T19:03:55.724494 #1]  INFO -- :   Rendering layouts/base.html.erb
redmine_1  | D, [2020-04-21T19:03:55.726048 #1] DEBUG -- :   UserPreference Load (0.4ms)  SELECT  `user_preferences`.* FROM `user_preferences` WHERE `user_preferences`.`user_id` = 1 LIMIT 1
redmine_1  | I, [2020-04-21T19:03:55.727002 #1]  INFO -- :   Rendered plugins/redmineup_tags/app/views/tags/_additional_assets.html.erb (0.3ms)
redmine_1  | D, [2020-04-21T19:03:55.730145 #1] DEBUG -- :   Project Load (0.3ms)  SELECT `projects`.`id`, `projects`.`name`, `projects`.`identifier`, `projects`.`lft`, `projects`.`rgt` FROM `projects` INNER JOIN `members` ON `projects`.`id` = `members`.`project_id` WHERE `members`.`user_id` = 1 AND `projects`.`status` != 9 AND `projects`.`status` = 1
redmine_1  | I, [2020-04-21T19:03:55.731610 #1]  INFO -- :   Rendered plugins/redmineup_tags/app/views/tags/_select2_transformation_rules.html.erb (0.1ms)
redmine_1  | I, [2020-04-21T19:03:55.731645 #1]  INFO -- :   Rendered layouts/base.html.erb (7.1ms)
redmine_1  | I, [2020-04-21T19:03:55.731782 #1]  INFO -- : Completed 200 OK in 30ms (Views: 14.0ms | ActiveRecord: 7.8ms)
redmine_1  | I, [2020-04-21T19:03:57.488626 #1]  INFO -- : Started GET "/core_fields/5/edit" for 172.27.0.1 at 2020-04-21 19:03:57 +0000
redmine_1  | I, [2020-04-21T19:03:57.489645 #1]  INFO -- : Processing by CoreFieldsController#edit as HTML
redmine_1  | I, [2020-04-21T19:03:57.489697 #1]  INFO -- :   Parameters: {"id"=>"5"}
redmine_1  | D, [2020-04-21T19:03:57.503862 #1] DEBUG -- :   Token Update All (12.1ms)  UPDATE `tokens` SET `tokens`.`updated_on` = '2020-04-21 19:03:57' WHERE `tokens`.`user_id` = 1 AND `tokens`.`value` = '928a8485b48111c08b3080e4b789a9002622d584' AND `tokens`.`action` = 'session'
redmine_1  | D, [2020-04-21T19:03:57.504667 #1] DEBUG -- :    (0.3ms)  SELECT MAX(`settings`.`updated_on`) FROM `settings`
redmine_1  | D, [2020-04-21T19:03:57.505748 #1] DEBUG -- :   User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 1 LIMIT 1
redmine_1  | I, [2020-04-21T19:03:57.506199 #1]  INFO -- :   Current user: admin (id=1)
redmine_1  | D, [2020-04-21T19:03:57.507198 #1] DEBUG -- :   CoreField Load (0.3ms)  SELECT  `core_fields`.* FROM `core_fields` WHERE `core_fields`.`id` = 5 LIMIT 1
redmine_1  | I, [2020-04-21T19:03:57.508137 #1]  INFO -- :   Rendering plugins/redmine_customize_core_fields/app/views/core_fields/edit.html.erb within layouts/admin
redmine_1  | D, [2020-04-21T19:03:57.510522 #1] DEBUG -- :   Role Load (0.5ms)  SELECT `roles`.* FROM `roles` WHERE `roles`.`builtin` = 0 ORDER BY `roles`.`position` ASC, `roles`.`builtin` ASC
redmine_1  | D, [2020-04-21T19:03:57.513139 #1] DEBUG -- :   Role Exists (0.5ms)  SELECT  1 AS one FROM `roles` INNER JOIN `core_fields_roles` ON `roles`.`id` = `core_fields_roles`.`role_id` WHERE `core_fields_roles`.`core_field_id` = 5 AND `roles`.`id` = 3 LIMIT 1
redmine_1  | D, [2020-04-21T19:03:57.514846 #1] DEBUG -- :   Role Exists (0.3ms)  SELECT  1 AS one FROM `roles` INNER JOIN `core_fields_roles` ON `roles`.`id` = `core_fields_roles`.`role_id` WHERE `core_fields_roles`.`core_field_id` = 5 AND `roles`.`id` = 4 LIMIT 1
redmine_1  | D, [2020-04-21T19:03:57.516099 #1] DEBUG -- :   Role Exists (0.2ms)  SELECT  1 AS one FROM `roles` INNER JOIN `core_fields_roles` ON `roles`.`id` = `core_fields_roles`.`role_id` WHERE `core_fields_roles`.`core_field_id` = 5 AND `roles`.`id` = 5 LIMIT 1
redmine_1  | D, [2020-04-21T19:03:57.517130 #1] DEBUG -- :   Role Exists (0.2ms)  SELECT  1 AS one FROM `roles` INNER JOIN `core_fields_roles` ON `roles`.`id` = `core_fields_roles`.`role_id` WHERE `core_fields_roles`.`core_field_id` = 5 AND `roles`.`id` = 6 LIMIT 1
redmine_1  | I, [2020-04-21T19:03:57.517922 #1]  INFO -- :   Rendered plugins/redmine_customize_core_fields/app/views/core_fields/edit.html.erb within layouts/admin (9.7ms)
redmine_1  | I, [2020-04-21T19:03:57.522563 #1]  INFO -- :   Rendered admin/_menu.html.erb (4.0ms)
redmine_1  | I, [2020-04-21T19:03:57.522773 #1]  INFO -- :   Rendering layouts/base.html.erb
redmine_1  | D, [2020-04-21T19:03:57.524355 #1] DEBUG -- :   UserPreference Load (0.4ms)  SELECT  `user_preferences`.* FROM `user_preferences` WHERE `user_preferences`.`user_id` = 1 LIMIT 1
redmine_1  | I, [2020-04-21T19:03:57.525285 #1]  INFO -- :   Rendered plugins/redmineup_tags/app/views/tags/_additional_assets.html.erb (0.3ms)
redmine_1  | D, [2020-04-21T19:03:57.528917 #1] DEBUG -- :   Project Load (0.5ms)  SELECT `projects`.`id`, `projects`.`name`, `projects`.`identifier`, `projects`.`lft`, `projects`.`rgt` FROM `projects` INNER JOIN `members` ON `projects`.`id` = `members`.`project_id` WHERE `members`.`user_id` = 1 AND `projects`.`status` != 9 AND `projects`.`status` = 1
redmine_1  | I, [2020-04-21T19:03:57.530515 #1]  INFO -- :   Rendered plugins/redmineup_tags/app/views/tags/_select2_transformation_rules.html.erb (0.2ms)
redmine_1  | I, [2020-04-21T19:03:57.530552 #1]  INFO -- :   Rendered layouts/base.html.erb (7.7ms)
redmine_1  | I, [2020-04-21T19:03:57.530686 #1]  INFO -- : Completed 200 OK in 41ms (Views: 20.4ms | ActiveRecord: 15.6ms)
redmine_1  | I, [2020-04-21T19:04:05.475165 #1]  INFO -- : Started PUT "/core_fields/is_private" for 172.27.0.1 at 2020-04-21 19:04:05 +0000
redmine_1  | I, [2020-04-21T19:04:05.476316 #1]  INFO -- : Processing by CoreFieldsController#update as HTML
redmine_1  | I, [2020-04-21T19:04:05.476407 #1]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"DGfToz9CiOmgw5+NS8HuXU0D7sdYyUUUVgO/PHsO4PCu4R7pMyFs+f7hUU18zvDbwrh9+XiR2RhRUU5kCuHCVQ==", "core_field"=>{"visible"=>"0", "role_ids"=>["3", "4", "5", "6", ""]}, "commit"=>"Save", "id"=>"is_private"}
redmine_1  | D, [2020-04-21T19:04:05.484400 #1] DEBUG -- :   Token Update All (5.9ms)  UPDATE `tokens` SET `tokens`.`updated_on` = '2020-04-21 19:04:05' WHERE `tokens`.`user_id` = 1 AND `tokens`.`value` = '928a8485b48111c08b3080e4b789a9002622d584' AND `tokens`.`action` = 'session'
redmine_1  | D, [2020-04-21T19:04:05.484903 #1] DEBUG -- :    (0.2ms)  SELECT MAX(`settings`.`updated_on`) FROM `settings`
redmine_1  | D, [2020-04-21T19:04:05.485774 #1] DEBUG -- :   User Load (0.2ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 1 LIMIT 1
redmine_1  | I, [2020-04-21T19:04:05.486013 #1]  INFO -- :   Current user: admin (id=1)
redmine_1  | D, [2020-04-21T19:04:05.486702 #1] DEBUG -- :   CoreField Load (0.3ms)  SELECT  `core_fields`.* FROM `core_fields` WHERE `core_fields`.`identifier` = 'is_private' LIMIT 1
redmine_1  | D, [2020-04-21T19:04:05.487507 #1] DEBUG -- :    (0.2ms)  BEGIN
redmine_1  | D, [2020-04-21T19:04:05.488338 #1] DEBUG -- :    (0.2ms)  COMMIT
redmine_1  | I, [2020-04-21T19:04:05.488969 #1]  INFO -- : Redirected to http://localhost:8080/core_fields/5/edit
redmine_1  | I, [2020-04-21T19:04:05.489112 #1]  INFO -- : Completed 302 Found in 13ms (ActiveRecord: 7.0ms)
redmine_1  | I, [2020-04-21T19:04:05.506660 #1]  INFO -- : Started GET "/core_fields/5/edit" for 172.27.0.1 at 2020-04-21 19:04:05 +0000
redmine_1  | I, [2020-04-21T19:04:05.507322 #1]  INFO -- : Processing by CoreFieldsController#edit as HTML
redmine_1  | I, [2020-04-21T19:04:05.507354 #1]  INFO -- :   Parameters: {"id"=>"5"}
redmine_1  | D, [2020-04-21T19:04:05.512295 #1] DEBUG -- :   Token Update All (3.6ms)  UPDATE `tokens` SET `tokens`.`updated_on` = '2020-04-21 19:04:05' WHERE `tokens`.`user_id` = 1 AND `tokens`.`value` = '928a8485b48111c08b3080e4b789a9002622d584' AND `tokens`.`action` = 'session'
redmine_1  | D, [2020-04-21T19:04:05.513125 #1] DEBUG -- :    (0.3ms)  SELECT MAX(`settings`.`updated_on`) FROM `settings`
redmine_1  | D, [2020-04-21T19:04:05.514611 #1] DEBUG -- :   User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 1 LIMIT 1
redmine_1  | I, [2020-04-21T19:04:05.515052 #1]  INFO -- :   Current user: admin (id=1)
redmine_1  | D, [2020-04-21T19:04:05.516041 #1] DEBUG -- :   CoreField Load (0.3ms)  SELECT  `core_fields`.* FROM `core_fields` WHERE `core_fields`.`id` = 5 LIMIT 1
redmine_1  | 172.27.0.1 - - [21/Apr/2020:19:04:05 UTC] "GET /core_fields/5/edit HTTP/1.1" 200 10526
redmine_1  | http://localhost:8080/core_fields/5/edit -> /core_fields/5/edit
redmine_1  | 172.27.0.1 - - [21/Apr/2020:19:04:05 UTC] "GET /javascripts/redmine_extensions/blocking_schedule.js?1587495580 HTTP/1.1" 304 0
redmine_1  | http://localhost:8080/core_fields/5/edit -> /javascripts/redmine_extensions/blocking_schedule.js?1587495580
redmine_1  | 172.27.0.1 - - [21/Apr/2020:19:04:05 UTC] "GET /javascripts/redmine_extensions/blocking_polyfill.js?1587495580 HTTP/1.1" 304 0
redmine_1  | 172.27.0.1 - - [21/Apr/2020:19:04:05 UTC] "GET /javascripts/redmine_extensions/blocking_render.js?1587495580 HTTP/1.1" 304 0
redmine_1  | 172.27.0.1 - - [21/Apr/2020:19:04:05 UTC] "GET /javascripts/redmine_extensions/blocking_module.js?1587495580 HTTP/1.1" 304 0
redmine_1  | http://localhost:8080/core_fields/5/edit -> /javascripts/redmine_extensions/blocking_polyfill.js?1587495580
redmine_1  | http://localhost:8080/core_fields/5/edit -> /javascripts/redmine_extensions/blocking_render.js?1587495580
redmine_1  | http://localhost:8080/core_fields/5/edit -> /javascripts/redmine_extensions/blocking_module.js?1587495580
redmine_1  | 172.27.0.1 - - [21/Apr/2020:19:04:05 UTC] "GET /javascripts/redmine_extensions/blocking_dynamic_loading.js?1587495580 HTTP/1.1" 304 0
redmine_1  | http://localhost:8080/core_fields/5/edit -> /javascripts/redmine_extensions/blocking_dynamic_loading.js?1587495580
redmine_1  | 172.27.0.1 - - [21/Apr/2020:19:04:05 UTC] "GET /javascripts/redmine_extensions/blocking_utils.js?1587495580 HTTP/1.1" 304 0
redmine_1  | http://localhost:8080/core_fields/5/edit -> /javascripts/redmine_extensions/blocking_utils.js?1587495580
redmine_1  | 172.27.0.1 - - [21/Apr/2020:19:04:05 UTC] "GET /javascripts/redmine_extensions/easy_togglers.js?1587495580 HTTP/1.1" 304 0
redmine_1  | 172.27.0.1 - - [21/Apr/2020:19:04:05 UTC] "GET /javascripts/redmine_extensions/jquery.entityarray.js?1587495580 HTTP/1.1" 304 0
redmine_1  | http://localhost:8080/core_fields/5/edit -> /javascripts/redmine_extensions/easy_togglers.js?1587495580
redmine_1  | http://localhost:8080/core_fields/5/edit -> /javascripts/redmine_extensions/jquery.entityarray.js?1587495580
redmine_1  | 172.27.0.1 - - [21/Apr/2020:19:04:05 UTC] "GET /javascripts/redmine_extensions/redmine_extensions.js?1587495580 HTTP/1.1" 304 0
redmine_1  | http://localhost:8080/core_fields/5/edit -> /javascripts/redmine_extensions/redmine_extensions.js?1587495580
```

My redmine values:

```


Environment:
  Redmine version                4.0.7.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.4
  Mercurial                      4.8.2
  Bazaar                         2.8.0
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  easy_baseline                  1.4
  easy_gantt                     1.12
  easy_gantt_pro                 1.10
  redmine_agile                  1.5.3
  redmine_base_deface            1.5.3
  redmine_customize_core_fields  1.0.0
  redmineup_tags                 2.0.8
```

**Comment by nanego** [comment]
Hello @axl89 
Is it possible for you to retry without any additional plugins (except "base_deface" and "customize_core_fields") ?
Just by moving them temporarily in another folder and restarting the application. It may help to ensure it does not come from a conflict with these plugins.

**Comment by axl89** [comment]
Just did it with a fresh docker image, no luck:

```
redmine_1  | 172.29.0.1 - - [21/Apr/2020:19:37:56 UTC] "POST /core_fields/is_private HTTP/1.1" 302 106
redmine_1  | http://localhost:8080/core_fields/5/edit -> /core_fields/is_private
redmine_1  | I, [2020-04-21T19:37:38.608317 #1]  INFO -- :   Current user: admin (id=1)
redmine_1  | D, [2020-04-21T19:37:38.608946 #1] DEBUG -- :   CoreField Load (0.2ms)  SELECT  `core_fields`.* FROM `core_fields` WHERE `core_fields`.`id` = 13 LIMIT 1
redmine_1  | I, [2020-04-21T19:37:38.609404 #1]  INFO -- :   Rendering plugins/redmine_customize_core_fields/app/views/core_fields/edit.html.erb within layouts/admin
redmine_1  | D, [2020-04-21T19:37:38.610759 #1] DEBUG -- :   Role Load (0.3ms)  SELECT `roles`.* FROM `roles` WHERE `roles`.`builtin` = 0 ORDER BY `roles`.`position` ASC, `roles`.`builtin` ASC
redmine_1  | D, [2020-04-21T19:37:38.612135 #1] DEBUG -- :   Role Exists (0.3ms)  SELECT  1 AS one FROM `roles` INNER JOIN `core_fields_roles` ON `roles`.`id` = `core_fields_roles`.`role_id` WHERE `core_fields_roles`.`core_field_id` = 13 AND `roles`.`id` = 3 LIMIT 1
redmine_1  | D, [2020-04-21T19:37:38.612976 #1] DEBUG -- :   Role Exists (0.3ms)  SELECT  1 AS one FROM `roles` INNER JOIN `core_fields_roles` ON `roles`.`id` = `core_fields_roles`.`role_id` WHERE `core_fields_roles`.`core_field_id` = 13 AND `roles`.`id` = 4 LIMIT 1
redmine_1  | I, [2020-04-21T19:37:38.613365 #1]  INFO -- :   Rendered plugins/redmine_customize_core_fields/app/views/core_fields/edit.html.erb within layouts/admin (3.9ms)
redmine_1  | I, [2020-04-21T19:37:38.615893 #1]  INFO -- :   Rendered admin/_menu.html.erb (2.2ms)
redmine_1  | I, [2020-04-21T19:37:38.616021 #1]  INFO -- :   Rendering layouts/base.html.erb
redmine_1  | D, [2020-04-21T19:37:38.617230 #1] DEBUG -- :   UserPreference Load (0.3ms)  SELECT  `user_preferences`.* FROM `user_preferences` WHERE `user_preferences`.`user_id` = 1 LIMIT 1
redmine_1  | D, [2020-04-21T19:37:38.620551 #1] DEBUG -- :   Project Load (0.4ms)  SELECT `projects`.`id`, `projects`.`name`, `projects`.`identifier`, `projects`.`lft`, `projects`.`rgt` FROM `projects` INNER JOIN `members` ON `projects`.`id` = `members`.`project_id` WHERE `members`.`user_id` = 1 AND `projects`.`status` != 9 AND `projects`.`status` = 1
redmine_1  | I, [2020-04-21T19:37:38.621953 #1]  INFO -- :   Rendered layouts/base.html.erb (5.9ms)
redmine_1  | I, [2020-04-21T19:37:38.622099 #1]  INFO -- : Completed 200 OK in 24ms (Views: 11.2ms | ActiveRecord: 9.1ms)
redmine_1  | I, [2020-04-21T19:37:48.591003 #1]  INFO -- : Started GET "/core_fields/5/edit" for 172.29.0.1 at 2020-04-21 19:37:48 +0000
redmine_1  | I, [2020-04-21T19:37:48.592062 #1]  INFO -- : Processing by CoreFieldsController#edit as HTML
redmine_1  | I, [2020-04-21T19:37:48.592130 #1]  INFO -- :   Parameters: {"id"=>"5"}
redmine_1  | D, [2020-04-21T19:37:48.597401 #1] DEBUG -- :   Token Update All (3.4ms)  UPDATE `tokens` SET `tokens`.`updated_on` = '2020-04-21 19:37:48' WHERE `tokens`.`user_id` = 1 AND `tokens`.`value` = 'f6b61ae32f1d0f2569b66f0962cc3c40e6019f07' AND `tokens`.`action` = 'session'
redmine_1  | D, [2020-04-21T19:37:48.598019 #1] DEBUG -- :    (0.3ms)  SELECT MAX(`settings`.`updated_on`) FROM `settings`
redmine_1  | D, [2020-04-21T19:37:48.599092 #1] DEBUG -- :   User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 1 LIMIT 1
redmine_1  | I, [2020-04-21T19:37:48.599342 #1]  INFO -- :   Current user: admin (id=1)
redmine_1  | D, [2020-04-21T19:37:48.600019 #1] DEBUG -- :   CoreField Load (0.3ms)  SELECT  `core_fields`.* FROM `core_fields` WHERE `core_fields`.`id` = 5 LIMIT 1
redmine_1  | I, [2020-04-21T19:37:48.600542 #1]  INFO -- :   Rendering plugins/redmine_customize_core_fields/app/views/core_fields/edit.html.erb within layouts/admin
redmine_1  | D, [2020-04-21T19:37:48.602050 #1] DEBUG -- :   Role Load (0.4ms)  SELECT `roles`.* FROM `roles` WHERE `roles`.`builtin` = 0 ORDER BY `roles`.`position` ASC, `roles`.`builtin` ASC
redmine_1  | D, [2020-04-21T19:37:48.603357 #1] DEBUG -- :   Role Exists (0.3ms)  SELECT  1 AS one FROM `roles` INNER JOIN `core_fields_roles` ON `roles`.`id` = `core_fields_roles`.`role_id` WHERE `core_fields_roles`.`core_field_id` = 5 AND `roles`.`id` = 3 LIMIT 1
redmine_1  | D, [2020-04-21T19:37:48.604166 #1] DEBUG -- :   Role Exists (0.3ms)  SELECT  1 AS one FROM `roles` INNER JOIN `core_fields_roles` ON `roles`.`id` = `core_fields_roles`.`role_id` WHERE `core_fields_roles`.`core_field_id` = 5 AND `roles`.`id` = 4 LIMIT 1
redmine_1  | I, [2020-04-21T19:37:48.604536 #1]  INFO -- :   Rendered plugins/redmine_customize_core_fields/app/views/core_fields/edit.html.erb within layouts/admin (3.9ms)
redmine_1  | I, [2020-04-21T19:37:48.606922 #1]  INFO -- :   Rendered admin/_menu.html.erb (2.1ms)
redmine_1  | I, [2020-04-21T19:37:48.607042 #1]  INFO -- :   Rendering layouts/base.html.erb
redmine_1  | D, [2020-04-21T19:37:48.608632 #1] DEBUG -- :   UserPreference Load (0.4ms)  SELECT  `user_preferences`.* FROM `user_preferences` WHERE `user_preferences`.`user_id` = 1 LIMIT 1
redmine_1  | D, [2020-04-21T19:37:48.613480 #1] DEBUG -- :   Project Load (0.7ms)  SELECT `projects`.`id`, `projects`.`name`, `projects`.`identifier`, `projects`.`lft`, `projects`.`rgt` FROM `projects` INNER JOIN `members` ON `projects`.`id` = `members`.`project_id` WHERE `members`.`user_id` = 1 AND `projects`.`status` != 9 AND `projects`.`status` = 1
redmine_1  | I, [2020-04-21T19:37:48.615026 #1]  INFO -- :   Rendered layouts/base.html.erb (7.9ms)
redmine_1  | I, [2020-04-21T19:37:48.615205 #1]  INFO -- : Completed 200 OK in 23ms (Views: 12.8ms | ActiveRecord: 6.3ms)
redmine_1  | I, [2020-04-21T19:37:56.380625 #1]  INFO -- : Started PUT "/core_fields/is_private" for 172.29.0.1 at 2020-04-21 19:37:56 +0000
redmine_1  | I, [2020-04-21T19:37:56.381284 #1]  INFO -- : Processing by CoreFieldsController#update as HTML
redmine_1  | I, [2020-04-21T19:37:56.381326 #1]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"Gb1xcvK8FMWKqRJTwb7ZhwOr6M3Mvzj2T2HSMqe4Wsz7fMci8oZRiGpxFDmuGAteNSbUPTFzA/b8tyB3b5Dt2Q==", "core_field"=>{"visible"=>"0", "role_ids"=>["3", "4", ""]}, "commit"=>"Save", "id"=>"is_private"}
redmine_1  | D, [2020-04-21T19:37:56.400025 #1] DEBUG -- :   Token Update All (17.4ms)  UPDATE `tokens` SET `tokens`.`updated_on` = '2020-04-21 19:37:56' WHERE `tokens`.`user_id` = 1 AND `tokens`.`value` = 'f6b61ae32f1d0f2569b66f0962cc3c40e6019f07' AND `tokens`.`action` = 'session'
redmine_1  | D, [2020-04-21T19:37:56.400829 #1] DEBUG -- :    (0.4ms)  SELECT MAX(`settings`.`updated_on`) FROM `settings`
redmine_1  | D, [2020-04-21T19:37:56.402045 #1] DEBUG -- :   User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 1 LIMIT 1
redmine_1  | I, [2020-04-21T19:37:56.402456 #1]  INFO -- :   Current user: admin (id=1)
redmine_1  | D, [2020-04-21T19:37:56.403687 #1] DEBUG -- :   CoreField Load (0.4ms)  SELECT  `core_fields`.* FROM `core_fields` WHERE `core_fields`.`identifier` = 'is_private' LIMIT 1
redmine_1  | D, [2020-04-21T19:37:56.404517 #1] DEBUG -- :    (0.2ms)  BEGIN
redmine_1  | D, [2020-04-21T19:37:56.405386 #1] DEBUG -- :    (0.2ms)  COMMIT
redmine_1  | I, [2020-04-21T19:37:56.406034 #1]  INFO -- : Redirected to http://localhost:8080/core_fields/5/edit
redmine_1  | I, [2020-04-21T19:37:56.406182 #1]  INFO -- : Completed 302 Found in 25ms (ActiveRecord: 18.9ms)
redmine_1  | I, [2020-04-21T19:37:56.429592 #1]  INFO -- : Started GET "/core_fields/5/edit" for 172.29.0.1 at 2020-04-21 19:37:56 +0000
redmine_1  | I, [2020-04-21T19:37:56.430686 #1]  INFO -- : Processing by CoreFieldsController#edit as HTML
redmine_1  | I, [2020-04-21T19:37:56.430745 #1]  INFO -- :   Parameters: {"id"=>"5"}
redmine_1  | D, [2020-04-21T19:37:56.436724 #1] DEBUG -- :   Token Update All (3.7ms)  UPDATE `tokens` SET `tokens`.`updated_on` = '2020-04-21 19:37:56' WHERE `tokens`.`user_id` = 1 AND `tokens`.`value` = 'f6b61ae32f1d0f2569b66f0962cc3c40e6019f07' AND `tokens`.`action` = 'session'
redmine_1  | D, [2020-04-21T19:37:56.437839 #1] DEBUG -- :    (0.3ms)  SELECT MAX(`settings`.`updated_on`) FROM `settings`
redmine_1  | D, [2020-04-21T19:37:56.439250 #1] DEBUG -- :   User Load (0.2ms)  SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser') AND `users`.`status` = 1 AND `users`.`id` = 1 LIMIT 1
redmine_1  | 172.29.0.1 - - [21/Apr/2020:19:37:56 UTC] "GET /core_fields/5/edit HTTP/1.1" 200 8252
redmine_1  | http://localhost:8080/core_fields/5/edit -> /core_fields/5/edit
```

My redmine:

```


Environment:
  Redmine version                4.0.7.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.4
  Mercurial                      4.8.2
  Bazaar                         2.8.0
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  redmine_base_deface            1.5.3
  redmine_customize_core_fields  1.0.0
```

**Comment by axl89** [comment]
![image](https://user-images.githubusercontent.com/939418/79907771-72e75200-841a-11ea-8fd3-94f8a751ef3f.png)

From my poor understanding of how the data must be sent, it's sending an additional `"` field, which might be the cause of the error? Look at the `core_field[role_ids][]` field.

Please find the cURL below to try to replicate it:

```
curl 'http://localhost:8080/core_fields/is_private' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.7,es-ES;q=0.3' --compressed -H 'Referer: http://localhost:8080/core_fields/5/edit' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Origin: http://localhost:8080' -H 'Connection: keep-alive' -H 'Cookie: _redmine_session=QnBrdmRzU0VkQURNWk9MdEJIYkRvVU9rV3FSOEgrVXhiR3FidkhpV0ZnVzQ4ZzV6aDhpODliK2RxdzVOdHc0SC9MODRFUFRkN1JQUFk5enM0VDdmY3hjeWkyUjlGS21rQnlwbVl2Z1IrYkRMWTlUdUVVWnRZU3IrZlAxcy9hQzI5cVBuaEs3b0dYNlIvTVVtQWgxYUZSZUs4cS8ySE13cWRTLzRSNEtvaWtLUUx5eCtiYldjU1lPZHVoYlpBM1dWNUNsS0RXNVdWWlBEcE5PZ24yWDNoMGpudFFZdHhYVXlQc1pVVDdOeHB2RzVMZlhITlFTMS9zN0g2QzJQNU00RnFFV3dJU0hNbThEdmUyWnNVNENnMW1IK0preThtM21RSGNnU0xIWFFFZW1uUllCMDV5Uk5OU052bjV4cU8zVVAtLTNlRWlYYUgrcmNBdkcrWTZ5bEtmVVE9PQ%3D%3D--c45f7d17f63824cad43581a54aa43d8692007ac8' -H 'Upgrade-Insecure-Requests: 1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --data 'utf8=%E2%9C%93&_method=put&authenticity_token=qoSRo7kjh3LWsDSeatVM9j2tdIj4KHin3DGs%2FGYi6sFIRSfzuRnCPzZoMvQFc54vCyBIeAXkQ6dv5165rgpd1A%3D%3D&core_field%5Bvisible%5D=0&core_field%5Brole_ids%5D%5B%5D=3&core_field%5Brole_ids%5D%5B%5D=4&core_field%5Brole_ids%5D%5B%5D=&commit=Save'
```

**Comment by nicolas-pages-scalefast** [comment]
Hi ! To give additional informatrion, I tried in a very clean configuration (fresh 4.0.9 Redmine vanilla, plus only the 2 plugins "redmine_base_deface" and "redmine_customize_core_fields", empty database).

Everything works fine, I see the "Standard Fields" entry in the settings, but any attempt of modification is just reverted. 

I tried something, by forcing the values in the database, by populating the tables "core_fields" and "core_fields_roles", and not the settings view shows a modification, but the field visibility is not applied (the field I was trying to hide for a specific role is still visible for that role). 

I wonder if it's not more related to redmine_base_deface then. 

For the 2 plugins, I have the last source revisions.

Thanks for your lights !!

**Comment by NicoP84** [comment]
Hi ! To give additional informatrion, I tried in a very clean configuration (fresh 4.0.9 Redmine vanilla, plus only the 2 plugins "redmine_base_deface" and "redmine_customize_core_fields", empty database).

Everything works fine, I see the "Standard Fields" entry in the settings, but any attempt of modification is just reverted.

I tried something, by forcing the values in the database, by populating the tables "core_fields" and "core_fields_roles", and not the settings view shows a modification, but the field visibility is not applied (the field I was trying to hide for a specific role is still visible for that role).

I wonder if it's not more related to redmine_base_deface then.

For the 2 plugins, I have the last source revisions.

Thanks for your lights !!

**Comment by nanego** [comment]
I just fixed the issue.
Please update the plugin and you should be able to save the settings.

**Comment by NicoP84** [comment]
It's better, thank you !! The selection is now saved ! 

Anyway, the standard fields are still visible even if I configure them not to be visible. Or did I misunderstand something ? I tried, for example to hide the standard field "% done" for a specific role. Then I create a user with this role, and I open an issue -> the "% done" still appears.

Again, thank you for your help

**Comment by nanego** [comment]
Just fixed a second bug. Please try again.
And do not forget to activate the module for each project.

**Comment by NicoP84** [comment]
Thanks. Everything works now. 
I have another question that I will ask in a separate topic, but this Issue can be closed, as it's clearly fixed.

**Comment by nanego** [comment]
Thank you for validating this fix!
