### ISSUE TITLE
The fields configured as "invisible" can be seen

### ISSUE THREAD

**Issue by NicoP84** [nanego/redmine_customize_core_fields#12]
A field set as invisible is not seen in the Issue page, in visualisation or in edit mode. 

Anyway, these values can be seen some other locations.

Example: 
- in the issues list, the field can be added as a column in the table;
- in the issues list, the field can be added as a filter;

And in many other places, depending on the selected field (example, the "% done" can be seen in the gantt view, also. 

I don't know if that was in the initial scope of this plugin, but it could be very helpful to hide the invisible fields from any place !

**Comment by nanego** [comment]
Hello
The issue has been fixed by @voondo in this pull request #13.
Please try the last version and tell us if everything works fine.

**Comment by NicoP84** [comment]
Everything is working fine... almost :)
The only missing part I can see from here is that the fields can still be seen in the available filters, even for roles that should not see them. 

I don't know the ruby syntax, but I assume (maybe wrongly) that something may not be correct ins this part of the file "query_patch.rb" : 

`def available_filters`
`    filters = super`
`    disabled_fields = CoreField.not_visible_identifiers(project)`
`    filters.reject{|o| name_matches_disabled_fields? disabled_fields, o.to_s }`
`  end`

We're close to the perfect functionality !

**Comment by NicoP84** [comment]
My bad, it was a side effect with another plugin (redmineup_tags). 

So, it's working exactly as I hoped ! The issue can be closed. 

Thanks and congrats !

**Comment by spachy** [comment]
Hi, I got the same issue than NicoP84 and it's not fixed for me.  
- Redmine version                4.1.1.stable
- Redmine Base Deface plugin 1.5.3 
- Redmine Customize Core Fields plugin 1.0.0

Could you confirm that this plugin works with the latest stable Redmine version ?

Thanks a lot.

**Comment by andreav** [comment]
Hello same problem here.

* Redmine version: 4.1.1.stable
* Redmine Base Deface plugin: 1.5.3
* Redmine Customize Core Fields plugin: master

I removed all plugins but Redmine Base Deface plugin and Redmine Customize Core Fields but still have the problem. Hidden fiedls are visible

**Comment by andreav** [comment]
I do not know if this can help, 
but when I visit issue page, I see this warning inside logs:

```
[1;32mDeface: [WARNING][0m No :original defined for 'replace_default_form', you should change its definition to include:
 :original => 'cf7d5d551db25d330ebed443cb49d79dff167e44' 
  Rendered issues/_trackers_description.html.erb (1.6ms)
  Rendered issues/_form_custom_fields.html.erb (1.1ms)
  Rendered issues/_attributes.html.erb (70.6ms)
  Rendered issues/_form.html.erb (221.8ms)
  Rendered attachments/_form.html.erb (6.2ms)
  Rendered issues/_edit.html.erb (339.4ms)
  Rendered issues/_action_menu_edit.html.erb (432.1ms)
  Rendered issues/_sidebar.html.erb (5.8ms)
  Rendered watchers/_watchers.html.erb (8.5ms)
  Rendered issues/show.html.erb within layouts/base (957.4ms)

```

**Comment by andreav** [comment]
I can confirm everything works great on my 4.1.1 installation. I just had to enable the plugin at project level.
